import { Geist, Geist_Mono, Fira_Sans } from "next/font/google";
import "./globals.css";
import TrustedForm from "./components/TrustedForm";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const firaSans = Fira_Sans({
    variable: "--font-fira-sans",
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${firaSans.variable} antialiased`}>
                <TrustedForm />
                {children}
            </body>
        </html>
    );
}